env: local

grpc:
  host: 0.0.0.0
  port: 9090

http:
  host: 0.0.0.0
  port: 8080

auth:
  access_token_secret: "local-dev-secret-change-me"
  access_token_ttl_minutes: 15
  issuer: "stock-trading-be"
  audience: "stock-trading-clients"
